version: 2.1

jobs:
  build-backend-docker-image:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run: cd backend && docker build . -t tutorium-backend:latest
  build-frontend-docker-image:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run: cd frontend && docker build . -t tutorium-frontend:latest
  lint-check-backend:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0-alpine
    resource_class: medium
    steps:
      - checkout
      - run: cd backend/TutoriumApi && dotnet restore
      - run: cd backend/TutoriumApi && dotnet format --verify-no-changes
  lint-check-frontend:
    docker:
      - image: cimg/node:16.18
    resource_class: medium
    steps:
      - checkout
      - run: cd frontend/TutoriumWeb && yarn
      - run: cd frontend/TutoriumWeb && yarn checks
  lint-check-meeting:
    docker:
      - image: cimg/node:16.18
    resource_class: medium
    steps:
      - checkout
      - run: cd meeting/TutoriumMeeting && yarn
      - run: cd meeting/TutoriumMeeting && yarn checks

workflows:
  lint-and-deploy:
    jobs:
      - lint-check-backend
      - lint-check-frontend
      - lint-check-meeting
      - build-backend-docker-image:
          requires:
            - lint-check-backend
      - build-frontend-docker-image:
          requires:
            - lint-check-frontend
      
