// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using tutorium.Data;

#nullable disable

namespace TutoriumApi.Migrations
{
    [DbContext(typeof(TutoriumContext))]
    [Migration("20221217193005_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("tutorium.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AffilatedCourseId")
                        .HasColumnType("integer");

                    b.Property<int>("AffilatedStudentId")
                        .HasColumnType("integer");

                    b.Property<int?>("CanceledBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AffilatedCourseId");

                    b.HasIndex("AffilatedStudentId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AffilatedCourseId = 1,
                            AffilatedStudentId = 1,
                            Date = new DateTime(2023, 2, 15, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AffilatedCourseId = 2,
                            AffilatedStudentId = 2,
                            Date = new DateTime(2023, 1, 15, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AffilatedCourseId = 2,
                            AffilatedStudentId = 2,
                            Date = new DateTime(2023, 1, 20, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AffilatedCourseId = 3,
                            AffilatedStudentId = 3,
                            Date = new DateTime(2023, 3, 30, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("tutorium.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AffilatedTutorId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Subject")
                        .HasColumnType("integer");

                    b.Property<int>("VerifiedStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AffilatedTutorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AffilatedTutorId = 4,
                            Description = "MAT101 Veriyorum",
                            Duration = 60,
                            Name = "MAT101",
                            Subject = 1,
                            VerifiedStatus = 0
                        },
                        new
                        {
                            Id = 2,
                            AffilatedTutorId = 4,
                            Description = "TOEFL Veriyorum",
                            DocumentPath = "/fake/path",
                            Duration = 90,
                            ExpirationDate = new DateTime(2023, 2, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TOEFL",
                            Subject = 0,
                            VerifiedStatus = 1
                        },
                        new
                        {
                            Id = 3,
                            AffilatedTutorId = 4,
                            Description = "GRE Veriyorum",
                            DocumentPath = "/fake/path",
                            Duration = 30,
                            ExpirationDate = new DateTime(2023, 3, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GRE",
                            Subject = 0,
                            VerifiedStatus = 3
                        });
                });

            modelBuilder.Entity("tutorium.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AffilatedCourseId")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AffilatedCourseId");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AffilatedCourseId = 1,
                            FilePath = "/File/Path/Fake"
                        },
                        new
                        {
                            Id = 2,
                            AffilatedCourseId = 1,
                            FilePath = "/File/Path/Fake"
                        },
                        new
                        {
                            Id = 3,
                            AffilatedCourseId = 2,
                            FilePath = "/File/Path/Fake"
                        });
                });

            modelBuilder.Entity("tutorium.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AffilatedCourseId")
                        .HasColumnType("integer");

                    b.Property<int>("AffilatedStudentId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(2, 1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AffilatedCourseId");

                    b.HasIndex("AffilatedStudentId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AffilatedCourseId = 1,
                            AffilatedStudentId = 1,
                            Comment = "Kotu",
                            CreatedAt = new DateTime(2023, 3, 30, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 9.8m,
                            UpdatedAt = new DateTime(2024, 3, 30, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AffilatedCourseId = 2,
                            AffilatedStudentId = 1,
                            Comment = "Iyi",
                            CreatedAt = new DateTime(2023, 4, 30, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 6.8m
                        },
                        new
                        {
                            Id = 3,
                            AffilatedCourseId = 2,
                            AffilatedStudentId = 3,
                            Comment = "Vasat",
                            CreatedAt = new DateTime(2023, 5, 30, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.8m
                        });
                });

            modelBuilder.Entity("tutorium.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailVerificationCode")
                        .HasColumnType("text");

                    b.Property<bool>("EmailVerifiedStatus")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneVerificationCode")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneVerifiedStatus")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("tutorium.Models.WhiteboardSave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AffilatedBookingId")
                        .HasColumnType("integer");

                    b.Property<string>("SavePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SaveTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AffilatedBookingId");

                    b.ToTable("WhiteboardSaves");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AffilatedBookingId = 1,
                            SavePath = "/File/Path/Fake",
                            SaveTime = new DateTime(2023, 3, 30, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AffilatedBookingId = 3,
                            SavePath = "/File/Path/Fake",
                            SaveTime = new DateTime(2023, 3, 30, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AffilatedBookingId = 3,
                            SavePath = "/File/Path/Fake",
                            SaveTime = new DateTime(2023, 3, 30, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("tutorium.Models.Student", b =>
                {
                    b.HasBaseType("tutorium.Models.User");

                    b.HasDiscriminator().HasValue("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "baris@student",
                            EmailVerifiedStatus = true,
                            FirstName = "Baris Ogun",
                            LastName = "Yoruk",
                            PasswordHash = new byte[] { 234, 18, 151, 153, 51, 15, 195, 253, 25, 2, 31, 196, 247, 110, 20, 4, 201, 232, 254, 12, 150, 87, 67, 166, 247, 149, 186, 41, 215, 168, 27, 2, 106, 88, 38, 153, 23, 179, 223, 91, 3, 192, 184, 123, 204, 151, 60, 27, 66, 119, 242, 9, 209, 192, 165, 227, 170, 157, 182, 103, 144, 60, 172, 87 },
                            PasswordSalt = new byte[] { 139, 248, 149, 249, 3, 213, 126, 244, 47, 171, 90, 224, 123, 102, 175, 247, 106, 208, 237, 224, 12, 83, 67, 141, 149, 170, 93, 234, 176, 12, 221, 30, 171, 135, 12, 166, 131, 199, 43, 122, 32, 139, 54, 220, 242, 254, 18, 228, 162, 240, 109, 14, 116, 170, 33, 65, 202, 170, 73, 228, 125, 203, 1, 170, 112, 66, 63, 23, 47, 0, 1, 189, 135, 17, 212, 200, 171, 144, 86, 131, 202, 249, 52, 209, 243, 201, 73, 31, 219, 66, 9, 94, 156, 185, 42, 103, 220, 11, 181, 142, 169, 130, 236, 129, 5, 106, 94, 214, 110, 172, 192, 177, 94, 30, 189, 167, 219, 184, 53, 246, 46, 241, 232, 251, 0, 160, 108, 247 },
                            Phone = "00905075711001",
                            PhoneVerifiedStatus = true
                        },
                        new
                        {
                            Id = 2,
                            Email = "cagri@student",
                            EmailVerifiedStatus = true,
                            FirstName = "Mustafa Cagri",
                            LastName = "Durgut",
                            PasswordHash = new byte[] { 234, 18, 151, 153, 51, 15, 195, 253, 25, 2, 31, 196, 247, 110, 20, 4, 201, 232, 254, 12, 150, 87, 67, 166, 247, 149, 186, 41, 215, 168, 27, 2, 106, 88, 38, 153, 23, 179, 223, 91, 3, 192, 184, 123, 204, 151, 60, 27, 66, 119, 242, 9, 209, 192, 165, 227, 170, 157, 182, 103, 144, 60, 172, 87 },
                            PasswordSalt = new byte[] { 139, 248, 149, 249, 3, 213, 126, 244, 47, 171, 90, 224, 123, 102, 175, 247, 106, 208, 237, 224, 12, 83, 67, 141, 149, 170, 93, 234, 176, 12, 221, 30, 171, 135, 12, 166, 131, 199, 43, 122, 32, 139, 54, 220, 242, 254, 18, 228, 162, 240, 109, 14, 116, 170, 33, 65, 202, 170, 73, 228, 125, 203, 1, 170, 112, 66, 63, 23, 47, 0, 1, 189, 135, 17, 212, 200, 171, 144, 86, 131, 202, 249, 52, 209, 243, 201, 73, 31, 219, 66, 9, 94, 156, 185, 42, 103, 220, 11, 181, 142, 169, 130, 236, 129, 5, 106, 94, 214, 110, 172, 192, 177, 94, 30, 189, 167, 219, 184, 53, 246, 46, 241, 232, 251, 0, 160, 108, 247 },
                            Phone = "0000000000000",
                            PhoneVerifiedStatus = true
                        },
                        new
                        {
                            Id = 3,
                            Email = "oguzhan@student",
                            EmailVerificationCode = "1234",
                            EmailVerifiedStatus = false,
                            FirstName = "Oguzhan",
                            LastName = "Ozcelik",
                            PasswordHash = new byte[] { 234, 18, 151, 153, 51, 15, 195, 253, 25, 2, 31, 196, 247, 110, 20, 4, 201, 232, 254, 12, 150, 87, 67, 166, 247, 149, 186, 41, 215, 168, 27, 2, 106, 88, 38, 153, 23, 179, 223, 91, 3, 192, 184, 123, 204, 151, 60, 27, 66, 119, 242, 9, 209, 192, 165, 227, 170, 157, 182, 103, 144, 60, 172, 87 },
                            PasswordSalt = new byte[] { 139, 248, 149, 249, 3, 213, 126, 244, 47, 171, 90, 224, 123, 102, 175, 247, 106, 208, 237, 224, 12, 83, 67, 141, 149, 170, 93, 234, 176, 12, 221, 30, 171, 135, 12, 166, 131, 199, 43, 122, 32, 139, 54, 220, 242, 254, 18, 228, 162, 240, 109, 14, 116, 170, 33, 65, 202, 170, 73, 228, 125, 203, 1, 170, 112, 66, 63, 23, 47, 0, 1, 189, 135, 17, 212, 200, 171, 144, 86, 131, 202, 249, 52, 209, 243, 201, 73, 31, 219, 66, 9, 94, 156, 185, 42, 103, 220, 11, 181, 142, 169, 130, 236, 129, 5, 106, 94, 214, 110, 172, 192, 177, 94, 30, 189, 167, 219, 184, 53, 246, 46, 241, 232, 251, 0, 160, 108, 247 },
                            Phone = "0000000000000",
                            PhoneVerifiedStatus = true
                        });
                });

            modelBuilder.Entity("tutorium.Models.Tutor", b =>
                {
                    b.HasBaseType("tutorium.Models.User");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Tutor");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Email = "ozgur@tutor",
                            EmailVerifiedStatus = true,
                            FirstName = "Halil Ozgur",
                            LastName = "Demir",
                            PasswordHash = new byte[] { 234, 18, 151, 153, 51, 15, 195, 253, 25, 2, 31, 196, 247, 110, 20, 4, 201, 232, 254, 12, 150, 87, 67, 166, 247, 149, 186, 41, 215, 168, 27, 2, 106, 88, 38, 153, 23, 179, 223, 91, 3, 192, 184, 123, 204, 151, 60, 27, 66, 119, 242, 9, 209, 192, 165, 227, 170, 157, 182, 103, 144, 60, 172, 87 },
                            PasswordSalt = new byte[] { 139, 248, 149, 249, 3, 213, 126, 244, 47, 171, 90, 224, 123, 102, 175, 247, 106, 208, 237, 224, 12, 83, 67, 141, 149, 170, 93, 234, 176, 12, 221, 30, 171, 135, 12, 166, 131, 199, 43, 122, 32, 139, 54, 220, 242, 254, 18, 228, 162, 240, 109, 14, 116, 170, 33, 65, 202, 170, 73, 228, 125, 203, 1, 170, 112, 66, 63, 23, 47, 0, 1, 189, 135, 17, 212, 200, 171, 144, 86, 131, 202, 249, 52, 209, 243, 201, 73, 31, 219, 66, 9, 94, 156, 185, 42, 103, 220, 11, 181, 142, 169, 130, 236, 129, 5, 106, 94, 214, 110, 172, 192, 177, 94, 30, 189, 167, 219, 184, 53, 246, 46, 241, 232, 251, 0, 160, 108, 247 },
                            Phone = "0000000000000",
                            PhoneVerifiedStatus = true,
                            Description = "Selamlar"
                        },
                        new
                        {
                            Id = 5,
                            Email = "yusuf@tutor",
                            EmailVerifiedStatus = true,
                            FirstName = "Yusuf Mirac",
                            LastName = "Uyar",
                            PasswordHash = new byte[] { 234, 18, 151, 153, 51, 15, 195, 253, 25, 2, 31, 196, 247, 110, 20, 4, 201, 232, 254, 12, 150, 87, 67, 166, 247, 149, 186, 41, 215, 168, 27, 2, 106, 88, 38, 153, 23, 179, 223, 91, 3, 192, 184, 123, 204, 151, 60, 27, 66, 119, 242, 9, 209, 192, 165, 227, 170, 157, 182, 103, 144, 60, 172, 87 },
                            PasswordSalt = new byte[] { 139, 248, 149, 249, 3, 213, 126, 244, 47, 171, 90, 224, 123, 102, 175, 247, 106, 208, 237, 224, 12, 83, 67, 141, 149, 170, 93, 234, 176, 12, 221, 30, 171, 135, 12, 166, 131, 199, 43, 122, 32, 139, 54, 220, 242, 254, 18, 228, 162, 240, 109, 14, 116, 170, 33, 65, 202, 170, 73, 228, 125, 203, 1, 170, 112, 66, 63, 23, 47, 0, 1, 189, 135, 17, 212, 200, 171, 144, 86, 131, 202, 249, 52, 209, 243, 201, 73, 31, 219, 66, 9, 94, 156, 185, 42, 103, 220, 11, 181, 142, 169, 130, 236, 129, 5, 106, 94, 214, 110, 172, 192, 177, 94, 30, 189, 167, 219, 184, 53, 246, 46, 241, 232, 251, 0, 160, 108, 247 },
                            Phone = "0000000000000",
                            PhoneVerificationCode = "1234",
                            PhoneVerifiedStatus = false,
                            Description = "Merhaba arkadaslar"
                        });
                });

            modelBuilder.Entity("tutorium.Models.Booking", b =>
                {
                    b.HasOne("tutorium.Models.Course", "AffilatedCourse")
                        .WithMany("Bookings")
                        .HasForeignKey("AffilatedCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tutorium.Models.Student", "AffilatedStudent")
                        .WithMany("Bookings")
                        .HasForeignKey("AffilatedStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffilatedCourse");

                    b.Navigation("AffilatedStudent");
                });

            modelBuilder.Entity("tutorium.Models.Course", b =>
                {
                    b.HasOne("tutorium.Models.Tutor", "AffilatedTutor")
                        .WithMany("Courses")
                        .HasForeignKey("AffilatedTutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffilatedTutor");
                });

            modelBuilder.Entity("tutorium.Models.Material", b =>
                {
                    b.HasOne("tutorium.Models.Course", "AffilatedCourse")
                        .WithMany("Materials")
                        .HasForeignKey("AffilatedCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffilatedCourse");
                });

            modelBuilder.Entity("tutorium.Models.Review", b =>
                {
                    b.HasOne("tutorium.Models.Course", "AffilatedCourse")
                        .WithMany("Reviews")
                        .HasForeignKey("AffilatedCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tutorium.Models.Student", "AffilatedStudent")
                        .WithMany("Reviews")
                        .HasForeignKey("AffilatedStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffilatedCourse");

                    b.Navigation("AffilatedStudent");
                });

            modelBuilder.Entity("tutorium.Models.WhiteboardSave", b =>
                {
                    b.HasOne("tutorium.Models.Booking", "AffilatedBooking")
                        .WithMany("WhiteboardSaves")
                        .HasForeignKey("AffilatedBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffilatedBooking");
                });

            modelBuilder.Entity("tutorium.Models.Booking", b =>
                {
                    b.Navigation("WhiteboardSaves");
                });

            modelBuilder.Entity("tutorium.Models.Course", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Materials");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("tutorium.Models.Student", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("tutorium.Models.Tutor", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
