// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using tutorium.Data;

#nullable disable

namespace TutoriumApi.Migrations
{
    [DbContext(typeof(TutoriumContext))]
    partial class TutoriumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("tutorium.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AffilatedCourseId")
                        .HasColumnType("integer");

                    b.Property<int>("AffilatedStudentId")
                        .HasColumnType("integer");

                    b.Property<int?>("CanceledBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AffilatedCourseId");

                    b.HasIndex("AffilatedStudentId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AffilatedCourseId = 1,
                            AffilatedStudentId = 1,
                            Date = new DateTime(2023, 2, 15, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AffilatedCourseId = 2,
                            AffilatedStudentId = 2,
                            Date = new DateTime(2023, 1, 15, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AffilatedCourseId = 2,
                            AffilatedStudentId = 2,
                            Date = new DateTime(2023, 1, 20, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AffilatedCourseId = 3,
                            AffilatedStudentId = 3,
                            Date = new DateTime(2023, 3, 30, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("tutorium.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AffilatedTutorId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Subject")
                        .HasColumnType("integer");

                    b.Property<int>("VerifiedStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AffilatedTutorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AffilatedTutorId = 4,
                            Description = "MAT101 Veriyorum",
                            Duration = 60,
                            Name = "MAT101",
                            Subject = 1,
                            VerifiedStatus = 0
                        },
                        new
                        {
                            Id = 2,
                            AffilatedTutorId = 4,
                            Description = "TOEFL Veriyorum",
                            DocumentPath = "/fake/path",
                            Duration = 90,
                            ExpirationDate = new DateTime(2023, 2, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TOEFL",
                            Subject = 0,
                            VerifiedStatus = 1
                        },
                        new
                        {
                            Id = 3,
                            AffilatedTutorId = 4,
                            Description = "GRE Veriyorum",
                            DocumentPath = "/fake/path",
                            Duration = 30,
                            ExpirationDate = new DateTime(2023, 3, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GRE",
                            Subject = 0,
                            VerifiedStatus = 3
                        });
                });

            modelBuilder.Entity("tutorium.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AffilatedCourseId")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AffilatedCourseId");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AffilatedCourseId = 1,
                            FilePath = "/File/Path/Fake"
                        },
                        new
                        {
                            Id = 2,
                            AffilatedCourseId = 1,
                            FilePath = "/File/Path/Fake"
                        },
                        new
                        {
                            Id = 3,
                            AffilatedCourseId = 2,
                            FilePath = "/File/Path/Fake"
                        });
                });

            modelBuilder.Entity("tutorium.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AffilatedCourseId")
                        .HasColumnType("integer");

                    b.Property<int>("AffilatedStudentId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(2, 1)");

                    b.HasKey("Id");

                    b.HasIndex("AffilatedCourseId");

                    b.HasIndex("AffilatedStudentId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AffilatedCourseId = 1,
                            AffilatedStudentId = 1,
                            Comment = "Kotu",
                            Date = new DateTime(2023, 3, 30, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 9.8m
                        },
                        new
                        {
                            Id = 2,
                            AffilatedCourseId = 2,
                            AffilatedStudentId = 1,
                            Comment = "Iyi",
                            Date = new DateTime(2023, 4, 30, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 6.8m
                        },
                        new
                        {
                            Id = 3,
                            AffilatedCourseId = 2,
                            AffilatedStudentId = 3,
                            Comment = "Vasat",
                            Date = new DateTime(2023, 5, 30, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.8m
                        });
                });

            modelBuilder.Entity("tutorium.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailVerificationCode")
                        .HasColumnType("text");

                    b.Property<bool>("EmailVerifiedStatus")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneVerificationCode")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneVerifiedStatus")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("tutorium.Models.WhiteboardSave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AffilatedBookingId")
                        .HasColumnType("integer");

                    b.Property<string>("SavePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SaveTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AffilatedBookingId");

                    b.ToTable("WhiteboardSaves");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AffilatedBookingId = 1,
                            SavePath = "/File/Path/Fake",
                            SaveTime = new DateTime(2023, 3, 30, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AffilatedBookingId = 3,
                            SavePath = "/File/Path/Fake",
                            SaveTime = new DateTime(2023, 3, 30, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AffilatedBookingId = 3,
                            SavePath = "/File/Path/Fake",
                            SaveTime = new DateTime(2023, 3, 30, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("tutorium.Models.Student", b =>
                {
                    b.HasBaseType("tutorium.Models.User");

                    b.HasDiscriminator().HasValue("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "baris@student",
                            EmailVerifiedStatus = true,
                            FirstName = "Baris Ogun",
                            LastName = "Yoruk",
                            PasswordHash = new byte[] { 46, 120, 221, 209, 203, 75, 128, 21, 122, 10, 215, 126, 23, 197, 112, 37, 105, 148, 9, 1, 30, 116, 108, 233, 82, 65, 0, 44, 200, 145, 155, 191, 68, 57, 68, 228, 1, 107, 83, 86, 161, 162, 82, 55, 202, 82, 170, 221, 0, 61, 203, 11, 199, 0, 16, 13, 64, 85, 21, 236, 9, 51, 247, 212 },
                            PasswordSalt = new byte[] { 146, 42, 48, 131, 60, 140, 121, 209, 223, 195, 154, 182, 34, 220, 130, 162, 122, 107, 121, 23, 63, 8, 11, 24, 190, 252, 30, 170, 19, 180, 190, 22, 131, 216, 201, 74, 18, 183, 163, 172, 39, 248, 23, 237, 250, 59, 7, 124, 164, 146, 255, 99, 16, 161, 171, 36, 189, 99, 233, 91, 144, 179, 217, 53, 157, 199, 8, 165, 13, 2, 124, 143, 134, 91, 26, 227, 198, 68, 19, 155, 53, 29, 213, 244, 95, 149, 135, 44, 250, 183, 106, 156, 107, 74, 97, 114, 128, 215, 106, 149, 138, 111, 32, 209, 161, 214, 30, 216, 72, 108, 138, 56, 79, 236, 104, 186, 63, 209, 183, 172, 201, 103, 112, 200, 100, 162, 248, 156 },
                            Phone = "00905075711001",
                            PhoneVerifiedStatus = true
                        },
                        new
                        {
                            Id = 2,
                            Email = "cagri@student",
                            EmailVerifiedStatus = true,
                            FirstName = "Mustafa Cagri",
                            LastName = "Durgut",
                            PasswordHash = new byte[] { 46, 120, 221, 209, 203, 75, 128, 21, 122, 10, 215, 126, 23, 197, 112, 37, 105, 148, 9, 1, 30, 116, 108, 233, 82, 65, 0, 44, 200, 145, 155, 191, 68, 57, 68, 228, 1, 107, 83, 86, 161, 162, 82, 55, 202, 82, 170, 221, 0, 61, 203, 11, 199, 0, 16, 13, 64, 85, 21, 236, 9, 51, 247, 212 },
                            PasswordSalt = new byte[] { 146, 42, 48, 131, 60, 140, 121, 209, 223, 195, 154, 182, 34, 220, 130, 162, 122, 107, 121, 23, 63, 8, 11, 24, 190, 252, 30, 170, 19, 180, 190, 22, 131, 216, 201, 74, 18, 183, 163, 172, 39, 248, 23, 237, 250, 59, 7, 124, 164, 146, 255, 99, 16, 161, 171, 36, 189, 99, 233, 91, 144, 179, 217, 53, 157, 199, 8, 165, 13, 2, 124, 143, 134, 91, 26, 227, 198, 68, 19, 155, 53, 29, 213, 244, 95, 149, 135, 44, 250, 183, 106, 156, 107, 74, 97, 114, 128, 215, 106, 149, 138, 111, 32, 209, 161, 214, 30, 216, 72, 108, 138, 56, 79, 236, 104, 186, 63, 209, 183, 172, 201, 103, 112, 200, 100, 162, 248, 156 },
                            Phone = "0000000000000",
                            PhoneVerifiedStatus = true
                        },
                        new
                        {
                            Id = 3,
                            Email = "oguzhan@student",
                            EmailVerificationCode = "1234",
                            EmailVerifiedStatus = false,
                            FirstName = "Oguzhan",
                            LastName = "Ozcelik",
                            PasswordHash = new byte[] { 46, 120, 221, 209, 203, 75, 128, 21, 122, 10, 215, 126, 23, 197, 112, 37, 105, 148, 9, 1, 30, 116, 108, 233, 82, 65, 0, 44, 200, 145, 155, 191, 68, 57, 68, 228, 1, 107, 83, 86, 161, 162, 82, 55, 202, 82, 170, 221, 0, 61, 203, 11, 199, 0, 16, 13, 64, 85, 21, 236, 9, 51, 247, 212 },
                            PasswordSalt = new byte[] { 146, 42, 48, 131, 60, 140, 121, 209, 223, 195, 154, 182, 34, 220, 130, 162, 122, 107, 121, 23, 63, 8, 11, 24, 190, 252, 30, 170, 19, 180, 190, 22, 131, 216, 201, 74, 18, 183, 163, 172, 39, 248, 23, 237, 250, 59, 7, 124, 164, 146, 255, 99, 16, 161, 171, 36, 189, 99, 233, 91, 144, 179, 217, 53, 157, 199, 8, 165, 13, 2, 124, 143, 134, 91, 26, 227, 198, 68, 19, 155, 53, 29, 213, 244, 95, 149, 135, 44, 250, 183, 106, 156, 107, 74, 97, 114, 128, 215, 106, 149, 138, 111, 32, 209, 161, 214, 30, 216, 72, 108, 138, 56, 79, 236, 104, 186, 63, 209, 183, 172, 201, 103, 112, 200, 100, 162, 248, 156 },
                            Phone = "0000000000000",
                            PhoneVerifiedStatus = true
                        });
                });

            modelBuilder.Entity("tutorium.Models.Tutor", b =>
                {
                    b.HasBaseType("tutorium.Models.User");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Tutor");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Email = "ozgur@tutor",
                            EmailVerifiedStatus = true,
                            FirstName = "Halil Ozgur",
                            LastName = "Demir",
                            PasswordHash = new byte[] { 46, 120, 221, 209, 203, 75, 128, 21, 122, 10, 215, 126, 23, 197, 112, 37, 105, 148, 9, 1, 30, 116, 108, 233, 82, 65, 0, 44, 200, 145, 155, 191, 68, 57, 68, 228, 1, 107, 83, 86, 161, 162, 82, 55, 202, 82, 170, 221, 0, 61, 203, 11, 199, 0, 16, 13, 64, 85, 21, 236, 9, 51, 247, 212 },
                            PasswordSalt = new byte[] { 146, 42, 48, 131, 60, 140, 121, 209, 223, 195, 154, 182, 34, 220, 130, 162, 122, 107, 121, 23, 63, 8, 11, 24, 190, 252, 30, 170, 19, 180, 190, 22, 131, 216, 201, 74, 18, 183, 163, 172, 39, 248, 23, 237, 250, 59, 7, 124, 164, 146, 255, 99, 16, 161, 171, 36, 189, 99, 233, 91, 144, 179, 217, 53, 157, 199, 8, 165, 13, 2, 124, 143, 134, 91, 26, 227, 198, 68, 19, 155, 53, 29, 213, 244, 95, 149, 135, 44, 250, 183, 106, 156, 107, 74, 97, 114, 128, 215, 106, 149, 138, 111, 32, 209, 161, 214, 30, 216, 72, 108, 138, 56, 79, 236, 104, 186, 63, 209, 183, 172, 201, 103, 112, 200, 100, 162, 248, 156 },
                            Phone = "0000000000000",
                            PhoneVerifiedStatus = true,
                            Description = "Selamlar"
                        },
                        new
                        {
                            Id = 5,
                            Email = "yusuf@tutor",
                            EmailVerifiedStatus = true,
                            FirstName = "Yusuf Mirac",
                            LastName = "Uyar",
                            PasswordHash = new byte[] { 46, 120, 221, 209, 203, 75, 128, 21, 122, 10, 215, 126, 23, 197, 112, 37, 105, 148, 9, 1, 30, 116, 108, 233, 82, 65, 0, 44, 200, 145, 155, 191, 68, 57, 68, 228, 1, 107, 83, 86, 161, 162, 82, 55, 202, 82, 170, 221, 0, 61, 203, 11, 199, 0, 16, 13, 64, 85, 21, 236, 9, 51, 247, 212 },
                            PasswordSalt = new byte[] { 146, 42, 48, 131, 60, 140, 121, 209, 223, 195, 154, 182, 34, 220, 130, 162, 122, 107, 121, 23, 63, 8, 11, 24, 190, 252, 30, 170, 19, 180, 190, 22, 131, 216, 201, 74, 18, 183, 163, 172, 39, 248, 23, 237, 250, 59, 7, 124, 164, 146, 255, 99, 16, 161, 171, 36, 189, 99, 233, 91, 144, 179, 217, 53, 157, 199, 8, 165, 13, 2, 124, 143, 134, 91, 26, 227, 198, 68, 19, 155, 53, 29, 213, 244, 95, 149, 135, 44, 250, 183, 106, 156, 107, 74, 97, 114, 128, 215, 106, 149, 138, 111, 32, 209, 161, 214, 30, 216, 72, 108, 138, 56, 79, 236, 104, 186, 63, 209, 183, 172, 201, 103, 112, 200, 100, 162, 248, 156 },
                            Phone = "0000000000000",
                            PhoneVerificationCode = "1234",
                            PhoneVerifiedStatus = false,
                            Description = "Merhaba arkadaslar"
                        });
                });

            modelBuilder.Entity("tutorium.Models.Booking", b =>
                {
                    b.HasOne("tutorium.Models.Course", "AffilatedCourse")
                        .WithMany("Bookings")
                        .HasForeignKey("AffilatedCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tutorium.Models.Student", "AffilatedStudent")
                        .WithMany("Bookings")
                        .HasForeignKey("AffilatedStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffilatedCourse");

                    b.Navigation("AffilatedStudent");
                });

            modelBuilder.Entity("tutorium.Models.Course", b =>
                {
                    b.HasOne("tutorium.Models.Tutor", "AffilatedTutor")
                        .WithMany("Courses")
                        .HasForeignKey("AffilatedTutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffilatedTutor");
                });

            modelBuilder.Entity("tutorium.Models.Material", b =>
                {
                    b.HasOne("tutorium.Models.Course", "AffilatedCourse")
                        .WithMany("Materials")
                        .HasForeignKey("AffilatedCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffilatedCourse");
                });

            modelBuilder.Entity("tutorium.Models.Review", b =>
                {
                    b.HasOne("tutorium.Models.Course", "AffilatedCourse")
                        .WithMany("Reviews")
                        .HasForeignKey("AffilatedCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tutorium.Models.Student", "AffilatedStudent")
                        .WithMany()
                        .HasForeignKey("AffilatedStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffilatedCourse");

                    b.Navigation("AffilatedStudent");
                });

            modelBuilder.Entity("tutorium.Models.WhiteboardSave", b =>
                {
                    b.HasOne("tutorium.Models.Booking", "AffilatedBooking")
                        .WithMany("WhiteboardSaves")
                        .HasForeignKey("AffilatedBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffilatedBooking");
                });

            modelBuilder.Entity("tutorium.Models.Booking", b =>
                {
                    b.Navigation("WhiteboardSaves");
                });

            modelBuilder.Entity("tutorium.Models.Course", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Materials");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("tutorium.Models.Student", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("tutorium.Models.Tutor", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
